export const getMenu = () => [
  {
    id: "1",
    name: "Эспрессо",
    quantity: 1,
    price: 700,
    image: require("../assets/images/coffee1.png"),
    details: "Классический кофе",
    volume: "300 мл",
  },
  {
    id: "2",
    name: "Латте",
    quantity: 1,
    price: 800,
    image: require("../assets/images/coffee2.png"),
    details: "Некрепкий молочный кофе",
    volume: "300 мл",
  },
  {
    id: "3",
    name: "Капучино",
    quantity: 1,
    price: 900,
    image: require("../assets/images/coffee3.png"),
    details: "Классический кофе с молочной пенкой",
    volume: "300 мл",
  },
  {
    id: "4",
    name: "Американо",
    quantity: 1,
    price: 700,
    image: require("../assets/images/coffee4.png"),
    details: "Черный кофе на основе эспрессо",
    volume: "300 мл",
  },
  {
    id: "5",
    name: "Раф ванильный",
    quantity: 1,
    price: 1000,
    image: require("../assets/images/coffee5.png"),
    details: "Сливочный кофе с ванильным вкусом",
    volume: "400 мл",
  },
  {
    id: "6",
    name: "Флэт Уайт",
    quantity: 1,
    price: 900,
    image: require("../assets/images/coffee3.png"),
    details: "Кофе покрепче с небольшой молочной пенкой",
    volume: "250 мл",
  },
];
